services:
  database:
    container_name: "cardgame-database"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Senha123!
    networks:
      - "cardgame"
    volumes:
       - "./db_volume:/mssql/data"

  # backend:
  #   depends_on:
  #     - database
  #   container_name: "cardgame-backend"
  #   build: "."
  #   ports:
  #     - 5000:5000
  #   networks:
  #     - "cardgame"
networks:
  cardgame:
    driver: bridge
volumes:
  db_volume: