services:
  database:
    container_name: "cardgame-database"
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports: 
      - 1433:1433
    environment:
      - ACCEPT_EULA=true
      - MSSQL_SA_PASSWORD=Senha123!
    networks:
      - "cardgame"
    # volumes:
    #    - "./db_volume:/mssql/data"

  # backend:
  #   depends_on:
  #     - database
  #   container_name: "cardgame-backend"
  #   build: "."
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - "cardgame"
  #   environment:
  #     - "ConnectionStrings__DefaultConnection=Server=cardgame-database;Database=master;User Id=sa;Password=Senha123!;MultipleActiveResultSets=true;Encrypt=YES;TrustServerCertificate=YES"
  #   command: >
  #     sh -c "dotnet ef database update -p app --no-build &&
  #            dotnet run"
networks:
  cardgame:
    driver: bridge
volumes:
  db_volume: